### ISSUE TITLE
安装问题

### ISSUE THREAD

**Issue by qchenac** [zhenze12345/fetch-audio-from-fm#12]

**Comment by qchenac** [comment]
我用mac，也按照wiki编译过一些程序，这个是不是也是要build一下才能用的那种。。。

**Comment by zhenggu** [comment]
mac自带ruby的，不用重新装的

**Comment by zhenggu** [comment]
所以你只要打开terminal, 然后sudo gem install oga os然后再装下brew: https://brew.sh/ 用brew install ffmpeg就可以了

**Comment by zhenggu** [comment]
不需要build 下载了脚本直接跑就好了 按照readme，当然先要装我之前发给你这些

**Comment by 178180793** [comment]
![image](https://user-images.githubusercontent.com/46117717/56491913-adbf5d00-651c-11e9-9da8-a23d35dc4517.png)
大哥报错了啊.

**Comment by zhenze12345** [comment]
我看到你的报错了，那个是open url超时

**Comment by zhenggu** [comment]
close for network issue
