### ISSUE TITLE
ximalaya failing due to a change in the div tag's class

### ISSUE THREAD

**Issue by davidb7** [zhenze12345/fetch-audio-from-fm#16]
The ximalaya script is failing [here](https://github.com/zhenze12345/fetch-audio-from-fm/blob/master/ximalaya#L47) because the class on the div tag seems to be changing. It used to be "_OO", a week or so ago I had to update it to "_c2" and now it is "_Vc".

A more generic xpath like "//li/div[contains(@class, "text")]/a" works, but there might be a better solution.

**Comment by zhenze12345** [comment]
thanks, I will take a look on it

**Comment by zhenggu** [comment]
merged the source code, close this issue
